version: '3.8'

services:
    app:
        build: .
        ports:
            - '5174:5174'
        environment:
            - NODE_ENV=production
            - VITE_API_URL=${VITE_API_URL}
            - VITE_APP_URL=${VITE_APP_URL}
        restart: unless-stopped
