[
    {
        resource: '/d:/Nick Savaya/Documents/ABS Designs/react/hotel-review-v2/sb1-gddswgel/src/lib/api.ts',
        owner: 'typescript',
        code: '2339',
        severity: 8,
        message: "Property 'retryCount' does not exist on type 'InternalAxiosRequestConfig<any>'.",
        source: 'ts',
        startLineNumber: 30,
        startColumn: 12,
        endLineNumber: 30,
        endColumn: 22,
    },
    {
        resource: '/d:/Nick Savaya/Documents/ABS Designs/react/hotel-review-v2/sb1-gddswgel/src/lib/api.ts',
        owner: 'typescript',
        code: '2339',
        severity: 8,
        message: "Property 'retryCount' does not exist on type 'InternalAxiosRequestConfig<any>'.",
        source: 'ts',
        startLineNumber: 30,
        startColumn: 32,
        endLineNumber: 30,
        endColumn: 42,
    },
];
